### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [RemoteSensingFrank/UAVProduct#2]
I tried to compile your project but failed. I look into the code and find that the openMVG you use is not the current one on the Github, which leads to lots of error.
Is there any idea about how to compile your code?
Thanks.

**Comment by RemoteSensingFrank** [comment]
yeah~I used the openmvg library  about 3 or 4 month ago. and could you plz show me your problem so that I can find out the problem.

**Comment by Yannnnnnnnnnnn** [comment]
After hours workd~~, I finally success! 
I will fork one branch and fix all the problem tomorrow.
Anyway thanks for all your work.

**Comment by RemoteSensingFrank** [comment]
:+1

**Comment by RemoteSensingFrank** [comment]
:+1
