### ISSUE TITLE
Some Test Data

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [RemoteSensingFrank/UAVProduct#4]
https://github.com/OpenDroneMap/odm_data

**Comment by RemoteSensingFrank** [comment]
great

**Comment by RemoteSensingFrank** [comment]
I add a GUI tools but  it  seems wrong  in  travis could you plz teach me  how to use travis

**Comment by Yannnnnnnnnnnn** [comment]
http://blog.csdn.net/u012348774/article/details/78663381
This is my note about the Travis CI.

**Comment by Yannnnnnnnnnnn** [comment]
I will look into the travis afternoon.

**Comment by Yannnnnnnnnnnn** [comment]
Another thing, I don't think it is a good idea to start build some GUI now, we still have lots of other things to do.
Maybe we can do it later~~
